[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "auto"

[runner]
fastReruns = true
enforceSerializableSessionState = false

[theme]
primaryColor = "#00d2d3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"

[global]
suppressDeprecationWarnings = true